# Generated by Django 3.1.1 on 2021-02-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(default='black', max_length=450),
            preserve_default=False,
        ),
    ]
