# Generated by Django 3.1.1 on 2021-02-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='genders',
            field=models.CharField(choices=[('men', 'men'), ('women', 'women'), ('unisex', 'unisex')], max_length=6),
        ),
    ]
