# Generated by Django 3.1.1 on 2021-02-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210212_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Easy Wear', max_length=450),
            preserve_default=False,
        ),
    ]
