# Generated by Django 3.1.1 on 2021-02-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='profiles/default.png', upload_to='profiles'),
        ),
    ]
