# Generated by Django 3.1.1 on 2021-02-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210220_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='items_in_cart',
            field=models.IntegerField(default=0),
        ),
    ]
